/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type ConfigObservation struct {
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// When true, tasks may exceed their reserved memory limit.
	// When true, tasks may exceed their reserved memory limit.
	MemoryOversubscriptionEnabled *bool `json:"memoryOversubscriptionEnabled,omitempty" tf:"memory_oversubscription_enabled,omitempty"`

	// Options to enable preemption for various schedulers.
	// Options to enable preemption for various schedulers.
	PreemptionConfig map[string]*bool `json:"preemptionConfig,omitempty" tf:"preemption_config,omitempty"`

	// Specifies whether scheduler binpacks or spreads allocations on available nodes. Possible values are binpack and spread.
	// Specifies whether scheduler binpacks or spreads allocations on available nodes.
	SchedulerAlgorithm *string `json:"schedulerAlgorithm,omitempty" tf:"scheduler_algorithm,omitempty"`
}

type ConfigParameters struct {

	// When true, tasks may exceed their reserved memory limit.
	// When true, tasks may exceed their reserved memory limit.
	// +kubebuilder:validation:Optional
	MemoryOversubscriptionEnabled *bool `json:"memoryOversubscriptionEnabled,omitempty" tf:"memory_oversubscription_enabled,omitempty"`

	// Options to enable preemption for various schedulers.
	// Options to enable preemption for various schedulers.
	// +kubebuilder:validation:Optional
	PreemptionConfig map[string]*bool `json:"preemptionConfig,omitempty" tf:"preemption_config,omitempty"`

	// Specifies whether scheduler binpacks or spreads allocations on available nodes. Possible values are binpack and spread.
	// Specifies whether scheduler binpacks or spreads allocations on available nodes.
	// +kubebuilder:validation:Optional
	SchedulerAlgorithm *string `json:"schedulerAlgorithm,omitempty" tf:"scheduler_algorithm,omitempty"`
}

// ConfigSpec defines the desired state of Config
type ConfigSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     ConfigParameters `json:"forProvider"`
}

// ConfigStatus defines the observed state of Config.
type ConfigStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ConfigObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// Config is the Schema for the Configs API. Manages scheduler configuration on the Nomad server.
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,nomad}
type Config struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              ConfigSpec   `json:"spec"`
	Status            ConfigStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ConfigList contains a list of Configs
type ConfigList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Config `json:"items"`
}

// Repository type metadata.
var (
	Config_Kind             = "Config"
	Config_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Config_Kind}.String()
	Config_KindAPIVersion   = Config_Kind + "." + CRDGroupVersion.String()
	Config_GroupVersionKind = CRDGroupVersion.WithKind(Config_Kind)
)

func init() {
	SchemeBuilder.Register(&Config{}, &ConfigList{})
}
