/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type Hcl2Observation struct {

	// Set this to true to be able to use
	// HCL2 filesystem functions
	// If true, HCL2 file system functions will be enabled when parsing the `jobspec`.
	AllowFs *bool `json:"allowFs,omitempty" tf:"allow_fs,omitempty"`

	// Set this to true if your jobspec uses the HCL2
	// format instead of the default HCL.
	// If true, the `jobspec` will be parsed as HCL2 instead of HCL.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// Additional variables to use when templating the job with HCL2
	Vars map[string]*string `json:"vars,omitempty" tf:"vars,omitempty"`
}

type Hcl2Parameters struct {

	// Set this to true to be able to use
	// HCL2 filesystem functions
	// If true, HCL2 file system functions will be enabled when parsing the `jobspec`.
	// +kubebuilder:validation:Optional
	AllowFs *bool `json:"allowFs,omitempty" tf:"allow_fs,omitempty"`

	// Set this to true if your jobspec uses the HCL2
	// format instead of the default HCL.
	// If true, the `jobspec` will be parsed as HCL2 instead of HCL.
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// Additional variables to use when templating the job with HCL2
	// +kubebuilder:validation:Optional
	Vars map[string]*string `json:"vars,omitempty" tf:"vars,omitempty"`
}

type JobObservation struct {

	// The IDs for allocations associated with this job.
	AllocationIds []*string `json:"allocationIds,omitempty" tf:"allocation_ids,omitempty"`

	// The target datacenters for the job, as derived from the jobspec.
	Datacenters []*string `json:"datacenters,omitempty" tf:"datacenters,omitempty"`

	// If detach = false, the ID for the deployment associated with the last job create/update, if one exists.
	DeploymentID *string `json:"deploymentId,omitempty" tf:"deployment_id,omitempty"`

	// If detach = false, the status for the deployment associated with the last job create/update, if one exists.
	DeploymentStatus *string `json:"deploymentStatus,omitempty" tf:"deployment_status,omitempty"`

	// If true, the job will be deregistered on destroy.
	DeregisterOnDestroy *bool `json:"deregisterOnDestroy,omitempty" tf:"deregister_on_destroy,omitempty"`

	// Determines if the job will be
	// deregistered if the ID of the job in the jobspec changes.
	// If true, the job will be deregistered when the job ID changes.
	DeregisterOnIDChange *bool `json:"deregisterOnIdChange,omitempty" tf:"deregister_on_id_change,omitempty"`

	// If true, the provider will return immediately
	// after creating or updating, instead of monitoring.
	// If true, the provider will return immediately after creating or updating, instead of monitoring.
	Detach *bool `json:"detach,omitempty" tf:"detach,omitempty"`

	// Options for the HCL2 jobspec parser.
	// Configuration for the HCL2 jobspec parser.
	Hcl2 []Hcl2Observation `json:"hcl2,omitempty" tf:"hcl2,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Set this to true if your jobspec is structured with
	// JSON instead of the default HCL.
	// If true, the `jobspec` will be parsed as json instead of HCL.
	JSON *bool `json:"json,omitempty" tf:"json,omitempty"`

	// The contents of the jobspec to register.
	// Job specification. If you want to point to a file use the file() function.
	Jobspec *string `json:"jobspec,omitempty" tf:"jobspec,omitempty"`

	// Integer that increments for each change. Used to detect any changes between plan and apply.
	ModifyIndex *string `json:"modifyIndex,omitempty" tf:"modify_index,omitempty"`

	// The name of the job, as derived from the jobspec.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The namespace of the job, as derived from the jobspec.
	Namespace *string `json:"namespace,omitempty" tf:"namespace,omitempty"`

	// Determines if the job will override any
	// soft-mandatory Sentinel policies and register even if they fail.
	// Override any soft-mandatory Sentinel policies that fail.
	PolicyOverride *bool `json:"policyOverride,omitempty" tf:"policy_override,omitempty"`

	// Set this to true if you want the job to
	// be purged when the resource is destroyed.
	// Whether to purge the job when the resource is destroyed.
	PurgeOnDestroy *bool `json:"purgeOnDestroy,omitempty" tf:"purge_on_destroy,omitempty"`

	// The target region for the job, as derived from the jobspec.
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	TaskGroups []TaskGroupsObservation `json:"taskGroups,omitempty" tf:"task_groups,omitempty"`

	// The type of the job, as derived from the jobspec.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type JobParameters struct {

	// Consul token used when registering this job.
	// Will fallback to the value declared in Nomad provider configuration, if any.
	// The Consul token used to submit this job.
	// +kubebuilder:validation:Optional
	ConsulTokenSecretRef *v1.SecretKeySelector `json:"consulTokenSecretRef,omitempty" tf:"-"`

	// If true, the job will be deregistered on destroy.
	// +kubebuilder:validation:Optional
	DeregisterOnDestroy *bool `json:"deregisterOnDestroy,omitempty" tf:"deregister_on_destroy,omitempty"`

	// Determines if the job will be
	// deregistered if the ID of the job in the jobspec changes.
	// If true, the job will be deregistered when the job ID changes.
	// +kubebuilder:validation:Optional
	DeregisterOnIDChange *bool `json:"deregisterOnIdChange,omitempty" tf:"deregister_on_id_change,omitempty"`

	// If true, the provider will return immediately
	// after creating or updating, instead of monitoring.
	// If true, the provider will return immediately after creating or updating, instead of monitoring.
	// +kubebuilder:validation:Optional
	Detach *bool `json:"detach,omitempty" tf:"detach,omitempty"`

	// Options for the HCL2 jobspec parser.
	// Configuration for the HCL2 jobspec parser.
	// +kubebuilder:validation:Optional
	Hcl2 []Hcl2Parameters `json:"hcl2,omitempty" tf:"hcl2,omitempty"`

	// Set this to true if your jobspec is structured with
	// JSON instead of the default HCL.
	// If true, the `jobspec` will be parsed as json instead of HCL.
	// +kubebuilder:validation:Optional
	JSON *bool `json:"json,omitempty" tf:"json,omitempty"`

	// The contents of the jobspec to register.
	// Job specification. If you want to point to a file use the file() function.
	// +kubebuilder:validation:Optional
	Jobspec *string `json:"jobspec,omitempty" tf:"jobspec,omitempty"`

	// Determines if the job will override any
	// soft-mandatory Sentinel policies and register even if they fail.
	// Override any soft-mandatory Sentinel policies that fail.
	// +kubebuilder:validation:Optional
	PolicyOverride *bool `json:"policyOverride,omitempty" tf:"policy_override,omitempty"`

	// Set this to true if you want the job to
	// be purged when the resource is destroyed.
	// Whether to purge the job when the resource is destroyed.
	// +kubebuilder:validation:Optional
	PurgeOnDestroy *bool `json:"purgeOnDestroy,omitempty" tf:"purge_on_destroy,omitempty"`

	// Vault token used when registering this job.
	// Will fallback to the value declared in Nomad provider configuration, if any.
	// The Vault token used to submit this job.
	// +kubebuilder:validation:Optional
	VaultTokenSecretRef *v1.SecretKeySelector `json:"vaultTokenSecretRef,omitempty" tf:"-"`
}

type TaskGroupsObservation struct {
	Count *float64 `json:"count,omitempty" tf:"count,omitempty"`

	Meta map[string]*string `json:"meta,omitempty" tf:"meta,omitempty"`

	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	Task []TaskObservation `json:"task,omitempty" tf:"task,omitempty"`

	Volumes []VolumesObservation `json:"volumes,omitempty" tf:"volumes,omitempty"`
}

type TaskGroupsParameters struct {
}

type TaskObservation struct {
	Driver *string `json:"driver,omitempty" tf:"driver,omitempty"`

	Meta map[string]*string `json:"meta,omitempty" tf:"meta,omitempty"`

	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	VolumeMounts []VolumeMountsObservation `json:"volumeMounts,omitempty" tf:"volume_mounts,omitempty"`
}

type TaskParameters struct {
}

type VolumeMountsObservation struct {
	Destination *string `json:"destination,omitempty" tf:"destination,omitempty"`

	ReadOnly *bool `json:"readOnly,omitempty" tf:"read_only,omitempty"`

	Volume *string `json:"volume,omitempty" tf:"volume,omitempty"`
}

type VolumeMountsParameters struct {
}

type VolumesObservation struct {
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	ReadOnly *bool `json:"readOnly,omitempty" tf:"read_only,omitempty"`

	Source *string `json:"source,omitempty" tf:"source,omitempty"`

	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type VolumesParameters struct {
}

// JobSpec defines the desired state of Job
type JobSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     JobParameters `json:"forProvider"`
}

// JobStatus defines the observed state of Job.
type JobStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        JobObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// Job is the Schema for the Jobs API. Manages the lifecycle of registering and deregistering Nomad jobs (applications).
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,nomad}
type Job struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="self.managementPolicy == 'ObserveOnly' || has(self.forProvider.jobspec)",message="jobspec is a required parameter"
	Spec   JobSpec   `json:"spec"`
	Status JobStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// JobList contains a list of Jobs
type JobList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Job `json:"items"`
}

// Repository type metadata.
var (
	Job_Kind             = "Job"
	Job_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Job_Kind}.String()
	Job_KindAPIVersion   = Job_Kind + "." + CRDGroupVersion.String()
	Job_GroupVersionKind = CRDGroupVersion.WithKind(Job_Kind)
)

func init() {
	SchemeBuilder.Register(&Job{}, &JobList{})
}
