/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type AuthMethodObservation struct {

	// Configuration specific to the auth method provider.
	Config []ConfigObservation `json:"config,omitempty" tf:"config,omitempty"`

	// Defines whether this ACL Auth Method is to be set
	// as default.
	// Defines whether this ACL Auth Method is to be set as default.
	Default *bool `json:"default,omitempty" tf:"default,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Defines the maximum life of a token
	// created by this method and is specified as a time duration such as "15h".
	// Defines the maximum life of a token created by this method.
	MaxTokenTTL *string `json:"maxTokenTtl,omitempty" tf:"max_token_ttl,omitempty"`

	// Defines whether the ACL Auth Method
	// creates a local or global token when performing SSO login. This field must be
	// set to either local or global.
	// Defines whether the ACL Auth Method creates a local or global token when performing SSO login. This field must be set to either "local" or "global".
	TokenLocality *string `json:"tokenLocality,omitempty" tf:"token_locality,omitempty"`

	// ACL Auth Method SSO workflow type. Currently,
	// the only supported type is OIDC.
	// ACL Auth Method SSO workflow type. Currently, the only supported type is "OIDC."
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type AuthMethodParameters struct {

	// Configuration specific to the auth method provider.
	// +kubebuilder:validation:Optional
	Config []ConfigParameters `json:"config,omitempty" tf:"config,omitempty"`

	// Defines whether this ACL Auth Method is to be set
	// as default.
	// Defines whether this ACL Auth Method is to be set as default.
	// +kubebuilder:validation:Optional
	Default *bool `json:"default,omitempty" tf:"default,omitempty"`

	// Defines the maximum life of a token
	// created by this method and is specified as a time duration such as "15h".
	// Defines the maximum life of a token created by this method.
	// +kubebuilder:validation:Optional
	MaxTokenTTL *string `json:"maxTokenTtl,omitempty" tf:"max_token_ttl,omitempty"`

	// Defines whether the ACL Auth Method
	// creates a local or global token when performing SSO login. This field must be
	// set to either local or global.
	// Defines whether the ACL Auth Method creates a local or global token when performing SSO login. This field must be set to either "local" or "global".
	// +kubebuilder:validation:Optional
	TokenLocality *string `json:"tokenLocality,omitempty" tf:"token_locality,omitempty"`

	// ACL Auth Method SSO workflow type. Currently,
	// the only supported type is OIDC.
	// ACL Auth Method SSO workflow type. Currently, the only supported type is "OIDC."
	// +kubebuilder:validation:Optional
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type ConfigObservation struct {

	// A list of allowed values that can be used for the redirect URI.
	AllowedRedirectUris []*string `json:"allowedRedirectUris,omitempty" tf:"allowed_redirect_uris,omitempty"`

	// List of auth claims that are valid for login.
	BoundAudiences []*string `json:"boundAudiences,omitempty" tf:"bound_audiences,omitempty"`

	// Mappings of claims (key) that will be copied to a metadata field (value).
	ClaimMappings map[string]*string `json:"claimMappings,omitempty" tf:"claim_mappings,omitempty"`

	// PEM encoded CA certs for use by the TLS client used to talk with the OIDC Discovery URL.
	DiscoveryCAPem []*string `json:"discoveryCaPem,omitempty" tf:"discovery_ca_pem,omitempty"`

	// Mappings of list claims (key) that will be copied to a metadata field (value).
	ListClaimMappings map[string]*string `json:"listClaimMappings,omitempty" tf:"list_claim_mappings,omitempty"`

	// The OAuth Client ID configured with the OIDC provider.
	OidcClientID *string `json:"oidcClientId,omitempty" tf:"oidc_client_id,omitempty"`

	// The OIDC Discovery URL, without any .well-known component (base path).
	OidcDiscoveryURL *string `json:"oidcDiscoveryUrl,omitempty" tf:"oidc_discovery_url,omitempty"`

	// List of OIDC scopes.
	OidcScopes []*string `json:"oidcScopes,omitempty" tf:"oidc_scopes,omitempty"`

	// A list of supported signing algorithms.
	SigningAlgs []*string `json:"signingAlgs,omitempty" tf:"signing_algs,omitempty"`
}

type ConfigParameters struct {

	// A list of allowed values that can be used for the redirect URI.
	// +kubebuilder:validation:Required
	AllowedRedirectUris []*string `json:"allowedRedirectUris" tf:"allowed_redirect_uris,omitempty"`

	// List of auth claims that are valid for login.
	// +kubebuilder:validation:Optional
	BoundAudiences []*string `json:"boundAudiences,omitempty" tf:"bound_audiences,omitempty"`

	// Mappings of claims (key) that will be copied to a metadata field (value).
	// +kubebuilder:validation:Optional
	ClaimMappings map[string]*string `json:"claimMappings,omitempty" tf:"claim_mappings,omitempty"`

	// PEM encoded CA certs for use by the TLS client used to talk with the OIDC Discovery URL.
	// +kubebuilder:validation:Optional
	DiscoveryCAPem []*string `json:"discoveryCaPem,omitempty" tf:"discovery_ca_pem,omitempty"`

	// Mappings of list claims (key) that will be copied to a metadata field (value).
	// +kubebuilder:validation:Optional
	ListClaimMappings map[string]*string `json:"listClaimMappings,omitempty" tf:"list_claim_mappings,omitempty"`

	// The OAuth Client ID configured with the OIDC provider.
	// +kubebuilder:validation:Required
	OidcClientID *string `json:"oidcClientId" tf:"oidc_client_id,omitempty"`

	// The OAuth Client Secret configured with the OIDC provider.
	// +kubebuilder:validation:Required
	OidcClientSecretSecretRef v1.SecretKeySelector `json:"oidcClientSecretSecretRef" tf:"-"`

	// The OIDC Discovery URL, without any .well-known component (base path).
	// +kubebuilder:validation:Required
	OidcDiscoveryURL *string `json:"oidcDiscoveryUrl" tf:"oidc_discovery_url,omitempty"`

	// List of OIDC scopes.
	// +kubebuilder:validation:Optional
	OidcScopes []*string `json:"oidcScopes,omitempty" tf:"oidc_scopes,omitempty"`

	// A list of supported signing algorithms.
	// +kubebuilder:validation:Optional
	SigningAlgs []*string `json:"signingAlgs,omitempty" tf:"signing_algs,omitempty"`
}

// AuthMethodSpec defines the desired state of AuthMethod
type AuthMethodSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     AuthMethodParameters `json:"forProvider"`
}

// AuthMethodStatus defines the observed state of AuthMethod.
type AuthMethodStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        AuthMethodObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// AuthMethod is the Schema for the AuthMethods API. Manages an ACL Auth Method in Nomad.
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,nomad}
type AuthMethod struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="self.managementPolicy == 'ObserveOnly' || has(self.forProvider.config)",message="config is a required parameter"
	// +kubebuilder:validation:XValidation:rule="self.managementPolicy == 'ObserveOnly' || has(self.forProvider.maxTokenTtl)",message="maxTokenTtl is a required parameter"
	// +kubebuilder:validation:XValidation:rule="self.managementPolicy == 'ObserveOnly' || has(self.forProvider.tokenLocality)",message="tokenLocality is a required parameter"
	// +kubebuilder:validation:XValidation:rule="self.managementPolicy == 'ObserveOnly' || has(self.forProvider.type)",message="type is a required parameter"
	Spec   AuthMethodSpec   `json:"spec"`
	Status AuthMethodStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// AuthMethodList contains a list of AuthMethods
type AuthMethodList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []AuthMethod `json:"items"`
}

// Repository type metadata.
var (
	AuthMethod_Kind             = "AuthMethod"
	AuthMethod_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: AuthMethod_Kind}.String()
	AuthMethod_KindAPIVersion   = AuthMethod_Kind + "." + CRDGroupVersion.String()
	AuthMethod_GroupVersionKind = CRDGroupVersion.WithKind(AuthMethod_Kind)
)

func init() {
	SchemeBuilder.Register(&AuthMethod{}, &AuthMethodList{})
}
