/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type BindingRuleObservation struct {

	// Name of the auth method for which this
	// rule applies to.
	// Name of the auth method for which this rule applies to.
	AuthMethod *string `json:"authMethod,omitempty" tf:"auth_method,omitempty"`

	// Target of the binding.
	// Target of the binding.
	BindName *string `json:"bindName,omitempty" tf:"bind_name,omitempty"`

	// Adjusts how this binding rule is applied
	// at login time. Valid values are role, policy, and management.
	// Adjusts how this binding rule is applied at login time. Valid values are "role" and "policy".
	BindType *string `json:"bindType,omitempty" tf:"bind_type,omitempty"`

	// Description for this ACL binding rule.
	// Description for this ACL binding rule.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// A boolean expression that matches against verified
	// identity attributes returned from the auth method during login.
	// A boolean expression that matches against verified identity attributes returned from the auth method during login.
	Selector *string `json:"selector,omitempty" tf:"selector,omitempty"`
}

type BindingRuleParameters struct {

	// Name of the auth method for which this
	// rule applies to.
	// Name of the auth method for which this rule applies to.
	// +kubebuilder:validation:Optional
	AuthMethod *string `json:"authMethod,omitempty" tf:"auth_method,omitempty"`

	// Target of the binding.
	// Target of the binding.
	// +kubebuilder:validation:Optional
	BindName *string `json:"bindName,omitempty" tf:"bind_name,omitempty"`

	// Adjusts how this binding rule is applied
	// at login time. Valid values are role, policy, and management.
	// Adjusts how this binding rule is applied at login time. Valid values are "role" and "policy".
	// +kubebuilder:validation:Optional
	BindType *string `json:"bindType,omitempty" tf:"bind_type,omitempty"`

	// Description for this ACL binding rule.
	// Description for this ACL binding rule.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// A boolean expression that matches against verified
	// identity attributes returned from the auth method during login.
	// A boolean expression that matches against verified identity attributes returned from the auth method during login.
	// +kubebuilder:validation:Optional
	Selector *string `json:"selector,omitempty" tf:"selector,omitempty"`
}

// BindingRuleSpec defines the desired state of BindingRule
type BindingRuleSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     BindingRuleParameters `json:"forProvider"`
}

// BindingRuleStatus defines the observed state of BindingRule.
type BindingRuleStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        BindingRuleObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// BindingRule is the Schema for the BindingRules API. Manages an ACL Binding Rule in Nomad.
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,nomad}
type BindingRule struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="self.managementPolicy == 'ObserveOnly' || has(self.forProvider.authMethod)",message="authMethod is a required parameter"
	// +kubebuilder:validation:XValidation:rule="self.managementPolicy == 'ObserveOnly' || has(self.forProvider.bindName)",message="bindName is a required parameter"
	// +kubebuilder:validation:XValidation:rule="self.managementPolicy == 'ObserveOnly' || has(self.forProvider.bindType)",message="bindType is a required parameter"
	Spec   BindingRuleSpec   `json:"spec"`
	Status BindingRuleStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// BindingRuleList contains a list of BindingRules
type BindingRuleList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []BindingRule `json:"items"`
}

// Repository type metadata.
var (
	BindingRule_Kind             = "BindingRule"
	BindingRule_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: BindingRule_Kind}.String()
	BindingRule_KindAPIVersion   = BindingRule_Kind + "." + CRDGroupVersion.String()
	BindingRule_GroupVersionKind = CRDGroupVersion.WithKind(BindingRule_Kind)
)

func init() {
	SchemeBuilder.Register(&BindingRule{}, &BindingRuleList{})
}
