/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type TokenObservation struct {

	// A non-sensitive identifier for this token that
	// can be logged and shared safely without granting any access to the cluster.
	// Nomad-generated ID for this token.
	AccessorID *string `json:"accessorId,omitempty" tf:"accessor_id,omitempty"`

	// The timestamp the token was created.
	// The timestamp the token was created.
	CreateTime *string `json:"createTime,omitempty" tf:"create_time,omitempty"`

	// Provides a TTL for the token in the form of
	// a time duration such as "5m" or "1h".
	// Provides a TTL for the token in the form of a time duration such as "5m" or "1h".
	ExpirationTTL *string `json:"expirationTtl,omitempty" tf:"expiration_ttl,omitempty"`

	// The timestamp after which the token is
	// considered expired and eligible for destruction.
	// The point after which a token is considered expired and eligible for destruction.
	ExpirationTime *string `json:"expirationTime,omitempty" tf:"expiration_time,omitempty"`

	// Whether the token should be replicated to all
	// regions, or if it will only be used in the region it was created in.
	// Whether the token should be replicated to all regions or not.
	Global *bool `json:"global,omitempty" tf:"global,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// A set of policy names to associate with this
	// token. Must be set on client-type tokens, must not be set on
	// management-type tokens. Policies do not need to exist before being
	// used here.
	// The ACL policies to associate with the token, if it's a 'client' type.
	Policies []*string `json:"policies,omitempty" tf:"policies,omitempty"`

	// The list of roles attached to the token. Each entry has
	// name and id attributes. It may be used multiple times.
	// The roles that should be applied to the token. It may be used multiple times.
	Role []TokenRoleObservation `json:"role,omitempty" tf:"role,omitempty"`

	// The type of token this is. Use client
	// for tokens that will have policies associated with them. Use management
	// for tokens that can perform any action.
	// The type of token to create, 'client' or 'management'.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type TokenParameters struct {

	// Provides a TTL for the token in the form of
	// a time duration such as "5m" or "1h".
	// Provides a TTL for the token in the form of a time duration such as "5m" or "1h".
	// +kubebuilder:validation:Optional
	ExpirationTTL *string `json:"expirationTtl,omitempty" tf:"expiration_ttl,omitempty"`

	// Whether the token should be replicated to all
	// regions, or if it will only be used in the region it was created in.
	// Whether the token should be replicated to all regions or not.
	// +kubebuilder:validation:Optional
	Global *bool `json:"global,omitempty" tf:"global,omitempty"`

	// A set of policy names to associate with this
	// token. Must be set on client-type tokens, must not be set on
	// management-type tokens. Policies do not need to exist before being
	// used here.
	// The ACL policies to associate with the token, if it's a 'client' type.
	// +kubebuilder:validation:Optional
	Policies []*string `json:"policies,omitempty" tf:"policies,omitempty"`

	// The list of roles attached to the token. Each entry has
	// name and id attributes. It may be used multiple times.
	// The roles that should be applied to the token. It may be used multiple times.
	// +kubebuilder:validation:Optional
	Role []TokenRoleParameters `json:"role,omitempty" tf:"role,omitempty"`

	// The type of token this is. Use client
	// for tokens that will have policies associated with them. Use management
	// for tokens that can perform any action.
	// The type of token to create, 'client' or 'management'.
	// +kubebuilder:validation:Optional
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type TokenRoleObservation struct {

	// The ID of the ACL role to link.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// A human-friendly name for this token.
	// The name of the ACL role linked.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type TokenRoleParameters struct {

	// The ID of the ACL role to link.
	// +kubebuilder:validation:Required
	ID *string `json:"id" tf:"id,omitempty"`
}

// TokenSpec defines the desired state of Token
type TokenSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     TokenParameters `json:"forProvider"`
}

// TokenStatus defines the observed state of Token.
type TokenStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        TokenObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// Token is the Schema for the Tokens API. Manages an ACL token in Nomad.
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,nomad}
type Token struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="self.managementPolicy == 'ObserveOnly' || has(self.forProvider.type)",message="type is a required parameter"
	Spec   TokenSpec   `json:"spec"`
	Status TokenStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// TokenList contains a list of Tokens
type TokenList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Token `json:"items"`
}

// Repository type metadata.
var (
	Token_Kind             = "Token"
	Token_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Token_Kind}.String()
	Token_KindAPIVersion   = Token_Kind + "." + CRDGroupVersion.String()
	Token_GroupVersionKind = CRDGroupVersion.WithKind(Token_Kind)
)

func init() {
	SchemeBuilder.Register(&Token{}, &TokenList{})
}
