---
apiVersion: nomad.nomad.upbound.io/v1alpha1
kind: Job
metadata:
  annotations:
    meta.upbound.io/example-id: nomad/v1alpha1/job
  labels:
    testing.upbound.io/example-name: example-job
  name: example-job
spec:
  forProvider:
    deregisterOnDestroy: true
    deregisterOnIdChange: true
    detach: true
    hcl2:
    - allowFs: true
      enabled: true
      # Specify the number of these tasks we want.
      vars:
        alphacount: "5"
        betacount: "4"
        deltacount: "3"
    policyOverride: true
    purgeOnDestroy: true
    json: false
    jobspec: |
      variable "alphacount" {
        type = number
      }
      variable "betacount" {
        type = number
      }
      variable "deltacount" {
        type = number
      }
      job "example" {
        region = "global"
        datacenters = ["us-east-1"]
        type = "service"
        update {
          stagger      = "3s"
          max_parallel = 3
        }
        group "alpha" {
          count = var.alphacount
          task "sleep" {
            driver = "exec"

            config {
              command = "/bin/sleep"
              args    = ["300"]
            }
          }
        }
        group "beta" {
          count = var.betacount
          task "sleep" {
            driver = "exec"

            config {
              command = "/bin/sleep"
              args    = ["300"]
            }
          }
        }
        group "delta" {
          count = var.deltacount
          task "sleep" {
            driver = "exec"

            config {
              command = "/bin/sleep"
              args    = ["300"]
            }
          }
        }
      }