---
apiVersion: nomad.nomad.upbound.io/v1alpha1
kind: Job
metadata:
  name: test-job
spec:
  forProvider:
    deregisterOnDestroy: true
    deregisterOnIdChange: true
    detach: true
    hcl2:
    - allowFs: true
      enabled: true
      vars:
    jobspec: |
      job "example" {
        region = "global"
        datacenters = ["us-east-1"]
        type = "service"
        update {
          stagger      = "3s"
          max_parallel = 3
        }
        group "alpha" {
          # Specify the number of these tasks we want.
          count = 5
          task "sleep" {
            driver = "exec"

            config {
              command = "/bin/sleep"
              args    = ["300"]
            }
          }
        }
        group "beta" {
          # Specify the number of these tasks we want.
          count = 4
          task "sleep" {
            driver = "exec"

            config {
              command = "/bin/sleep"
              args    = ["300"]
            }
          }
        }
        group "delta" {
          # Specify the number of these tasks we want.
          count = 3
          task "sleep" {
            driver = "exec"

            config {
              command = "/bin/sleep"
              args    = ["300"]
            }
          }
        }
      }
    policyOverride: true
    purgeOnDestroy: true
#  need an inline jobspec example