apiVersion: nomad.nomad.upbound.io/v1alpha1
kind: Job
metadata:
  annotations:
    meta.upbound.io/example-id: nomad/v1alpha1/job
  labels:
    testing.upbound.io/example-name: app
  name: app
spec:
  forProvider:
    jobspec: ${file("${path.module}/jobspec.hcl")}

---

