apiVersion: nomad.nomad.upbound.io/v1alpha1
kind: NomadNamespace
metadata:
  annotations:
    meta.upbound.io/example-id: nomad/v1alpha1/nomadnamespace
  labels:
    testing.upbound.io/example-name: dev
  name: dev
spec:
  forProvider:
    description: Shared development environment.
    meta:
      foo: bar
      owner: John Doe
    quota: dev

---

